- src/main/resources/jnt_serverSettingsSystemInfos/html/serverSettingsSystemInfos.jsp
- src/main/resources/jnt_serverSettingsSystemInfos/html/serverSettingsSystemInfos.settingsBootstrap3GoogleMaterialStyle.jsp
https://jira.jahia.org/browse/QA-12375
> QA-12375 : remove system tab information

- pom.xml
- src/main/java/org/jahia/modules/serversettings/flow/WebprojectHandler.java
- src/main/resources/css/manageWebProjects.css
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/flow.xml
https://jira.jahia.org/browse/BACKLOG-11635
- increase version of the module to next major, since we need to update the core dependency to the latest version.
- implement a new method in WebProjectHandler to check is the site limit has been reached
> BACKLOG-11635 increase version of the module to next major

- src/main/resources/css/manageWebProjects.css
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.flow/view.jsp
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/BACKLOG-11632
replace blur effect by opacity so one can understand the are is disabled
> BACKLOG-11632 replace blurring by opacity

- pom.xml
https://jira.jahia.org/browse/BACKLOG-11875
> BACKLOG-11875 : Add module signature

- pom.xml
https://jira.jahia.org/browse/BACKLOG-12378
Downgrade node to make it build on bamboo
> BACKLOG-12378 Change node version to 11.11.0 (from 13.2.0)

- package.json
- yarn.lock
https://jira.jahia.org/browse/BACKLOG-12268
Register with Jahia 8 (new end point)
> BACKLOG-12268 Make it possible to register with new endpoint

- src/main/resources/javascript/locales/de.json
https://jira.jahia.org/browse/BACKLOG-12702
Add german translation
> Backlog 12702

- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/BACKLOG-12531
Send message via Message API to top window with the updated list of sites and the default site
> BACKLOG-12531: Send message via Message API to top window

- src/javascript/serverSettings/aboutJahia/registerRoutes.js
- src/javascript/serverSettings/configuration/registerRoutes.js
- src/javascript/serverSettings/systemComponents/registerRoutes.js
- src/javascript/serverSettings/systemHealth/registerRoutes.js
- src/javascript/serverSettings/usersAndRoles/registerRoutes.js
- src/javascript/serverSettings/webProjects/registerRoutes.js
https://jira.jahia.org/browse/PROJECT-XXX
> BACKLOG-12820: Adapted adminRoute format

- src/javascript/serverSettings/aboutJahia/registerRoutes.js
- src/javascript/serverSettings/configuration/registerRoutes.js
- src/javascript/serverSettings/systemComponents/registerRoutes.js
- src/javascript/serverSettings/systemHealth/registerRoutes.js
- src/javascript/serverSettings/usersAndRoles/registerRoutes.js
- src/javascript/serverSettings/webProjects/registerRoutes.js
- src/main/resources/javascript/locales/de.json
- src/main/resources/javascript/locales/en.json
- src/main/resources/javascript/locales/es.json
- src/main/resources/javascript/locales/fr.json
- src/main/resources/javascript/locales/it.json
- src/main/resources/javascript/locales/pt.json
https://jira.jahia.org/browse/BACKLOG-12935
Simple reordering of the server administration panels + moved the "Report an issue" entry below the About Jahia section. Moved the license panel in this about Jahia section.
> BACKLOG-12935: reordering of the server settings

- src/main/resources/javascript/locales/de.json
- src/main/resources/javascript/locales/en.json
- src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-12936
Updated labels for the administration panels
> BACKLOG-12936: Fixed labels in server settings

- LICENSE.txt
- pom.xml
- src/main/java/org/jahia/modules/serversettings/cache/CacheManagement.java
- src/main/java/org/jahia/modules/serversettings/flow/AdminPropertiesHandler.java
- src/main/java/org/jahia/modules/serversettings/flow/CacheManagerHandler.java
- src/main/java/org/jahia/modules/serversettings/flow/ImportInfo.java
- src/main/java/org/jahia/modules/serversettings/flow/SiteBean.java
- src/main/java/org/jahia/modules/serversettings/flow/WebprojectHandler.java
- src/main/java/org/jahia/modules/serversettings/flow/validator/MailSettingsValidator.java
- src/main/java/org/jahia/modules/serversettings/flow/validator/SearchSettingsValidator.java
- src/main/java/org/jahia/modules/serversettings/memoryThread/MemoryThreadInformationManagement.java
- src/main/java/org/jahia/modules/serversettings/portlets/AssemblerTask.java
- src/main/java/org/jahia/modules/serversettings/portlets/BasePortletHelper.java
- src/main/java/org/jahia/modules/serversettings/portlets/JBossPortletHelper.java
- src/main/java/org/jahia/modules/serversettings/portlets/ManagePortletsAction.java
- src/main/java/org/jahia/modules/serversettings/portlets/PreparedPortletsController.java
- src/main/java/org/jahia/modules/serversettings/portlets/WebSpherePortletHelper.java
- src/main/java/org/jahia/modules/serversettings/users/admin/AdminProperties.java
- src/main/resources/META-INF/LICENSE.txt
> BACKLOG-13160 - Updated copyright to 2020

- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.flow/view.jsp
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/BACKLOG-12252
> BACKLOG-12252 : renaming of editModeAccess permission

- pom.xml
- src/javascript/serverSettings/usersAndRoles/registerRoutes.js
- src/main/import/repository.xml
- src/main/resources/javascript/locales/de.json
- src/main/resources/javascript/locales/en.json
- src/main/resources/javascript/locales/fr.json
- src/main/resources/resources/JahiaServerSettings_en.properties
- src/main/resources/resources/JahiaServerSettings_fr.properties
https://jira.jahia.org/browse/BACKLOG-14170
> BACKLOG-14170: Add UI for tools access

- src/main/resources/javascript/locales/de.json
https://jira.jahia.org/browse/BACKLOG-14221
> BACKLOG-14221: Fixed translation

- pom.xml
- src/main/java/org/jahia/modules/serversettings/flow/WebprojectHandler.java
https://jira.jahia.org/browse/TECH-319
Replace LicenseCheckerService.Stub with LicenseCheckUtils as LicenseCheckerService.Stub is only available when bundle is deployed
> TECH-319: Adapt code for new license package

- pom.xml
Update the version and the scm tag that were not consistent with the branch and the prevous release
> QA-12266 : Update version and SCM tag

- .eslintignore
- src/main/resources/javascript/stringUtils.js
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.flow/view.jsp
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/QA-13522
Shorten string if too long. 
E.g:
`C:\Jahia-EnterpriseDistribution-8.0.3.0\digital-factory-data\exports` will be shorten to `C:\Jahia-EnterpriseDistr...\digital-factory-data\exports`
> QA-13522: Path Traversal Injection

- .circleci/.circleci.settings.xml
- .circleci/config.yml
- package.json
- yarn.lock
Jira ticket: https://jira.jahia.org/browse/BACKLOG-15966
> BACKLOG-15966 - Added Circleci Config and fixed security vulnerabilities

- .circleci/.circleci.settings.xml
- .circleci/config.yml
> BACKLOG-15966 - Added CircleCI config since bamboo build is disabled

- src/main/resources/jnt_serverSettingsSystemInfos/html/serverSettingsSystemInfos.settingsBootstrap3GoogleMaterialStyle.jsp
https://jira.jahia.org/browse/QA-13729
Filter System properties that contains "pass" (this includes DB_PASS, DB_PASSWORD, PASSWORD, etc) and "secret" (e.g SECRET_KEY, SECRET, etc)
> QA-13729: Passwords in clear text

- src/main/java/org/jahia/modules/serversettings/flow/ImportInfo.java
- src/main/java/org/jahia/modules/serversettings/flow/WebprojectHandler.java
https://jira.jahia.org/browse/BACKLOG-15965
Changed build number representation to String and use the new import method
> BACKLOG-15965 changed build number representation to String and use new import method

- .gitignore
- pom.xml
- src/main/java/org/jahia/modules/serversettings/flow/ImportInfo.java
- src/main/java/org/jahia/modules/serversettings/flow/WebprojectHandler.java
https://jira.jahia.org/browse/BACKLOG-15965
Removed build number as it is redundant in this project after new changes
> BACKLOG-15965 removed build number from the project as it is redundant

- src/main/java/org/jahia/modules/serversettings/flow/WebprojectHandler.java
https://jira.jahia.org/browse/QA-13823
Allows sitesKey to be bound
> QA-13823: Add getter to fix webflow binding

- src/main/resources/jnt_serverSettingsManagePortlets/html/serverSettingsManagePortlets.jsp
- src/main/resources/jnt_serverSettingsManagePortlets/html/serverSettingsManagePortlets.settingsBootstrap3GoogleMaterialStyle.jsp
https://jira.jahia.org/browse/QA-13172
Correct the version of the gwt-min.css
> QA-13172: correct gwt.min.css version

- src/main/resources/jnt_serverSettingsManagePortlets/html/serverSettingsManagePortlets.jsp
- src/main/resources/jnt_serverSettingsManagePortlets/html/serverSettingsManagePortlets.settingsBootstrap3GoogleMaterialStyle.jsp
https://jira.jahia.org/browse/QA-13172
Correct version of gwt.min.css
> QA-13172: correct gwt-min.css version

- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- .github/workflows/on-rollback.yml
- package.json
- yarn.lock
Also updated github actions to address deprecation warnings
> BACKLOG-16219: Updated dependencies to address dependabot warnings

- .github/dependabot.yml
- .github/workflows/on-code-change.yml
> BACKLOG-16219: Added dependabot to remove devDependencies

- .github/workflows/on-release.yml
- .github/workflows/on-rollback.yml
https://jira.jahia.org/browse/TECH-1081
Update deprecated steps
> TECH-1081 Update deprecated steps

- pom.xml
- src/main/import/repository.xml
https://jira.jahia.org/browse/TECH-1092
> TECH-1092: Remove unused TabularList dependency

- .eslintrc
- .github/workflows/on-code-change.yml
- .github/workflows/on-release.yml
- package.json
- pom.xml
- src/javascript/index.js
- src/javascript/init.js
- src/javascript/publicPath.js
- src/javascript/serverSettings/aboutJahia/registerRoutes.js
- src/javascript/serverSettings/configuration/registerRoutes.js
- src/javascript/serverSettings/systemComponents/registerRoutes.js
- src/javascript/serverSettings/systemHealth/registerRoutes.js
- src/javascript/serverSettings/usersAndRoles/registerRoutes.js
- src/javascript/serverSettings/webProjects/registerRoutes.js
- webpack.config.js
- yarn.lock
https://jira.jahia.org/browse/TECH-1220
> TECH-1220 : Upgrade webpack and dependencies, use module federation

- .github/workflows/nightly.yml
> Split pagerduty reporting between Jahia RL and Jahia SN

- pom.xml
https://jira.jahia.org/browse/BACKLOG-21788
> BACKLOG-21788 : remove app-shell from jahia-depends

- pom.xml
https://jira.jahia.org/browse/TECH-1416
> TECH-1416: Import guava as provided dependency

- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.flow/view.jsp
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/QA-14467
Possibility to display and select all websites .
> QA-14467: Possibility to display and select all websites

- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.flow/view.jsp
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/QA-14467
Change behavior of select all checkbox to select all sites across all pages using jquery datatables plugin API
> QA-14467: Fix select all checkbox for project management

- .github/workflows/on-code-change.yml
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.flow/view.jsp
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/QA-14467
backport PR for https://github.com/Jahia/serverSettings/pull/123
> QA-14467: Add ability to display and select all sites

- .github/maven.settings.xml
- .github/workflows/on-release.yml
https://jira.jahia.org/browse/BACKLOG-22955
Fix release issues
> BACKLOG-22955: Add missing maven credentials and fix checkout issue

- .github/maven.settings.xml
https://jira.jahia.org/browse/BACKLOG-22956
> BACKLOG-22956: Add missing maven credentials

- .github/workflows/on-release.yml
https://jira.jahia.org/browse/BACKLOG-22955
> BACKLOG-22955: Add missing param for Slack notif

- .github/workflows/nightly-rl.yml
- .github/workflows/nightly-sn.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- .github/workflows/on-rollback.yml
- .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
Upgrade actions
> TECH-1639 Upgrade actions

- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.flow/view.jsp
- src/main/resources/jnt_serverSettingsManageWebProjects/html/serverSettingsManageWebProjects.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
https://jira.jahia.org/browse/BACKLOG-23044
> BACKLOG-23044 : remove edit mode shortcut in webprojects for distant publication servers

- src/javascript/serverSettings/backgroundJobs/BackgroundJobs.gql-queries.js
- src/javascript/serverSettings/backgroundJobs/HistoryBackgroundJobsTable.jsx
- src/javascript/serverSettings/backgroundJobs/ScheduledBackgroundJobsTable.jsx
- src/main/resources/META-INF/patches/graphql/01-permissions.started.graphql
- src/main/resources/javascript/locales/de.json
- src/main/resources/javascript/locales/en.json
- src/main/resources/javascript/locales/fr.json
- tests/cypress/e2e/backgroundJobsTable/backgroundJobsTest.cy.ts
- tests/cypress/fixtures/testData/historyBackgroundJobs.json
- tests/cypress/fixtures/testData/scheduledBackgroundJobs.json
This PR adds a permissions migration script to allow server administrators to view the bg jobs page by default; also includes some minor styling fixes and test brittleness fix.
> BACKLOG-23323 Permissions migration script and styling

- .github/workflows/on-code-change.yml
- tests/provisioning-manifest-snapshot.yml
Updated the provisioning for the nightly (release) to use latest graphql-dxm-provider, needed for the latest serverSettings changes to work.
> BACKLOG-23323: update provisioning
